/**
 * Copyright (c) 2012-2013, Michael Yang 杨福海 (www.yangfuhai.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mfh.comn.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
/**
 * 来源于net.tsz.afinal.annotation.sqlite
 * 
 * @author zhangyz created on 2014-3-14
 */
@Target({ElementType.FIELD,ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME) 
public @interface Column {
    public String caption() default "";//add by zhangyz
	 public String name() default ""; //数据库列名
	 public String defaultValue() default "";

    /**
     * 该属性原来来自于net.sf.persist.annotations
     * If the field is auto-generated in the database (eg. auto increment
     * fields). This will hint the engine to avoid using the field in
     * insert/update automatic operations, and to let it know which fields must
     * be updated if updateAutoGeneratedKeys is set to true.
     */
    boolean autoGenerated() default false;
}
